In [2]:
import numpy as np 
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr1=np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr2=np.arange(20,40,2)
arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [10]:
arr=np.ones(9).reshape(3,3)
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr=np.random.randint(1,10,size=(4,4))
arr

array([[1, 2, 9, 5],
       [1, 5, 4, 4],
       [8, 6, 1, 4],
       [2, 4, 6, 9]], dtype=int32)

In [16]:
arr[1,:]=7

In [17]:
arr

array([[1, 2, 9, 5],
       [7, 7, 7, 7],
       [8, 6, 1, 4],
       [2, 4, 6, 9]], dtype=int32)

In [18]:
arr=[10,20,30,40,50]
for i in arr:
    if i>25:
        print(i)

30
40
50


In [21]:
arr1=np.random.randint(1,20,size=20)
arr1

array([ 6,  6, 15,  7, 19,  6, 13,  3,  5, 10, 15, 15, 15,  6, 11, 13,  8,
        6,  9,  3], dtype=int32)

In [32]:
data={
    'min':min(arr1),
    'max':max(arr1)
}
for mod,name in data.items():
     print(mod,name)

min 3
max 19


In [34]:
arr=np.random.randint(1,20,size=15)
arr

array([17,  9,  1, 19, 17,  3,  1,  1, 18, 19,  7,  6,  4, 18, 13],
      dtype=int32)

In [35]:
arr.sort

<function ndarray.sort>

In [40]:
arr1=arr.sort

In [44]:
arr1=np.sort(arr)

In [45]:
arr1

array([ 1,  1,  1,  3,  4,  6,  7,  9, 13, 17, 17, 18, 18, 19, 19],
      dtype=int32)

In [3]:
# 1 create a 1d numpy array with numbers from 0 to 9abs
import numpy as np 
arr=np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr1=np.random.randint(0,1,size=10)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [8]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [9]:
arr[0:3]

array([10, 20, 30])

In [10]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [12]:
arr1[::-1]

array([5, 4, 3, 2, 1])

In [14]:
arr2=np.random.randint(1,10,size=(3,3))
arr2

array([[9, 6, 4],
       [2, 3, 9],
       [7, 2, 2]], dtype=int32)

In [17]:
arr2[1:,1:]

array([[3, 9],
       [2, 2]], dtype=int32)

In [18]:
bool_index=arr2%2==0
bool_index

array([[False,  True,  True],
       [ True, False, False],
       [False,  True,  True]])

In [25]:
arr=arr2[bool_index]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [27]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [29]:
arr=arr[bool_index]

In [30]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
#Add two numpy array element wise 

arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
sum=arr1+arr2
sum

array([ 7,  9, 11, 13, 15])

In [36]:
mult=arr1*arr2
mult

array([ 6, 14, 24, 36, 50])

In [38]:
c=np.dot(arr1,arr2)
c

np.int64(130)

In [39]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

In [40]:
c=np.dot(A,B)

In [41]:
c

array([[ 58,  64],
       [139, 154]])

In [42]:
a=np.random.randint(1,9,size=(2,3))
b=np.random.randint(9,15,size=(3,2))

In [43]:
c=np.dot(a,b)

In [44]:
c

array([[164, 147],
       [138, 107]], dtype=int32)

In [45]:
a

array([[5, 3, 5],
       [1, 7, 3]], dtype=int32)

In [46]:
b

array([[14, 14],
       [13,  9],
       [11, 10]], dtype=int32)

In [54]:
mean_value=np.mean(a)
standrad_value=np.std(a)
median_value=np.median(a)
mean_value
# standrad_value

np.float64(4.0)

In [55]:
standrad_value

np.float64(1.9148542155126762)

In [56]:
median_value

np.float64(4.0)

In [58]:
import pandas as pd 

In [60]:
data =pd.DataFrame ({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Math": [78, 56, 90, 65, 88],
    "Science": [85, 64, 88, 70, 92],
    "English": [92, 70, 94, 72, 85],
    "History": [74, 60, 86, 68, 90]
})
data

Name  Math  Science  English  History
0    Alice    78       85       92       74
1      Bob    56       64       70       60
2  Charlie    90       88       94       86
3    David    65       70       72       68
4      Eva    88       92       85       90

In [62]:
#compute statistics mean ,median std deviation for each subject 

#using numpyA
math=np.array(data['Math'])
math

array([78, 56, 90, 65, 88])

In [63]:
sceince=np.array([data['Science']])
english=np.array([data['English']])
history=np.array([data['History']])

In [68]:
mean_value=np.mean(math)
median_value=np.median(math)
standrad_value=np.std(math)


np.float64(13.139254164525473)

In [70]:
mean_value


np.float64(75.4)

In [71]:
median_value


np.float64(78.0)

In [72]:
standrad_value

np.float64(13.139254164525473)

In [76]:
#for sceince student 
mean_value=np.mean(sceince)
median_value=np.median(sceince)
standrad_value=np.std(sceince)



In [77]:
mean_value

np.float64(79.8)

In [78]:
median_value

np.float64(85.0)

In [79]:
standrad_value

np.float64(10.85172797300043)

In [80]:
#for english 
mean_value=np.mean(english)
median_value=np.median(english)
standrad_value=np.std(english)


In [81]:
median_value

np.float64(85.0)

In [82]:
mean_value

np.float64(82.6)

In [83]:
standrad_value

np.float64(9.951884243699782)

In [84]:
mean_value=np.mean(history)
median_value=np.median(history)
standrad_value=np.std(history)


In [85]:
mean_value

np.float64(75.6)

In [86]:
median_value

np.float64(74.0)

In [87]:
standrad_value

np.float64(11.128342194594845)

In [88]:
data

Name  Math  Science  English  History
0    Alice    78       85       92       74
1      Bob    56       64       70       60
2  Charlie    90       88       94       86
3    David    65       70       72       68
4      Eva    88       92       85       90

In [93]:
# Topper in each subject
subject_toppers = {}
for subject in ["Math", "Science", "English", "History"]:
    topper = data.loc[data[subject].idxmax()]
    subject_toppers[subject] = topper["Name"]

print("Topper in each subject:", subject_toppers)


Topper in each subject: {'Math': 'Charlie', 'Science': 'Eva', 'English': 'Charlie', 'History': 'Eva'}


In [97]:
data['TotalMarks']=data[['Math','Science','English','History']].sum(axis=1)
data

Name  Math  Science  English  History  TotalMarks
0    Alice    78       85       92       74         329
1      Bob    56       64       70       60         250
2  Charlie    90       88       94       86         358
3    David    65       70       72       68         275
4      Eva    88       92       85       90         355

In [99]:
data['Percentage']=data['TotalMarks']/4
data

Name  Math  Science  English  History  TotalMarks  Percentage
0    Alice    78       85       92       74         329       82.25
1      Bob    56       64       70       60         250       62.50
2  Charlie    90       88       94       86         358       89.50
3    David    65       70       72       68         275       68.75
4      Eva    88       92       85       90         355       88.75

In [104]:
correlation = data["Science"].corr(data["Math"])
correlation

np.float64(0.9754276672238572)

In [106]:
#for normalizations
subjects = data[["Math", "Science", "English", "History"]]
normalized = (subjects - subjects.min()) / (subjects.max() - subjects.min()) * 100



In [108]:
df_normalized = pd.concat([data["Name"], normalized], axis=1)
df_normalized


Name        Math     Science     English     History
0    Alice   64.705882   75.000000   91.666667   46.666667
1      Bob    0.000000    0.000000    0.000000    0.000000
2  Charlie  100.000000   85.714286  100.000000   86.666667
3    David   26.470588   21.428571    8.333333   26.666667
4      Eva   94.117647  100.000000   62.500000  100.000000

In [109]:
# another data
weather_data = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Chennai", "Kolkata", "Bangalore", "Hyderabad", "Jaipur"],
    "Temperature": [35, 30, 33, 34, 28, 32, 36],
    "Humidity": [40, 70, 65, 60, 55, 50, 35],
    "WindSpeed": [12, 8, 10, 9, 7, 11, 13],
    "Rainfall": [2, 15, 8, 12, 5, 6, 1]
})


In [131]:
details=weather_data[['Temperature','Humidity','WindSpeed','Rainfall']]
details

Temperature  Humidity  WindSpeed  Rainfall
0           35        40         12         2
1           30        70          8        15
2           33        65         10         8
3           34        60          9        12
4           28        55          7         5
5           32        50         11         6
6           36        35         13         1

In [113]:
weather_data.isna().sum()

City           0
Temperature    0
Humidity       0
WindSpeed      0
Rainfall       0
dtype: int64

In [114]:
weather_data.duplicated().sum()

np.int64(0)

In [119]:
weather_data.groupby('City')['Temperature'].max()

City
Bangalore    28
Chennai      33
Delhi        35
Hyderabad    32
Jaipur       36
Kolkata      34
Mumbai       30
Name: Temperature, dtype: int64

In [121]:
hottest_city=weather_data.loc[weather_data['Temperature'].idxmax(),'City']
hottest_city

'Jaipur'

In [124]:
humidity_city=weather_data.loc[weather_data['Humidity'].idxmax(),'City']
humidity_city

'Mumbai'

In [128]:
weather_data['FeelsLike']=(weather_data[['Temperature','Humidity']].sum(axis=1))/10-weather_data['WindSpeed']

In [129]:
weather_data

City  Temperature  Humidity  WindSpeed  Rainfall  FeelsLike
0      Delhi           35        40         12         2       -4.5
1     Mumbai           30        70          8        15        2.0
2    Chennai           33        65         10         8       -0.2
3    Kolkata           34        60          9        12        0.4
4  Bangalore           28        55          7         5        1.3
5  Hyderabad           32        50         11         6       -2.8
6     Jaipur           36        35         13         1       -5.9

In [133]:
normalized=(details-details.min())/(details.max()-details.min())*100
print(normalized)

   Temperature    Humidity   WindSpeed    Rainfall
0         87.5   14.285714   83.333333    7.142857
1         25.0  100.000000   16.666667  100.000000
2         62.5   85.714286   50.000000   50.000000
3         75.0   71.428571   33.333333   78.571429
4          0.0   57.142857    0.000000   28.571429
5         50.0   42.857143   66.666667   35.714286
6        100.0    0.000000  100.000000    0.000000


In [137]:
normalized_value=pd.concat([weather_data['City'],normalized],axis=1)
normalized_value

City  Temperature    Humidity   WindSpeed    Rainfall
0      Delhi         87.5   14.285714   83.333333    7.142857
1     Mumbai         25.0  100.000000   16.666667  100.000000
2    Chennai         62.5   85.714286   50.000000   50.000000
3    Kolkata         75.0   71.428571   33.333333   78.571429
4  Bangalore          0.0   57.142857    0.000000   28.571429
5  Hyderabad         50.0   42.857143   66.666667   35.714286
6     Jaipur        100.0    0.000000  100.000000    0.000000

In [139]:
#practice number 3A
sales_data = pd.DataFrame({
    "OrderID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hannah"],
    "Product": ["Laptop", "Mobile", "Headphones", "Laptop", "Mobile", "Tablet", "Laptop", "Headphones"],
    "Category": ["Electronics", "Electronics", "Accessories", "Electronics", "Electronics", "Electronics", "Electronics", "Accessories"],
    "Quantity": [1, 2, 1, 1, 3, 2, 1, 4],
    "Price": [75000, 25000, 2000, 80000, 26000, 30000, 70000, 2200],
    "Discount": [5000, 2000, 200, 8000, 3000, 2500, 4000, 400],
    "City": ["Delhi", "Mumbai", "Chennai", "Kolkata", "Delhi", "Bangalore", "Hyderabad", "Mumbai"]
})
sales_data



OrderID Customer     Product     Category  Quantity  Price  Discount  \
0      101    Alice      Laptop  Electronics         1  75000      5000   
1      102      Bob      Mobile  Electronics         2  25000      2000   
2      103  Charlie  Headphones  Accessories         1   2000       200   
3      104    David      Laptop  Electronics         1  80000      8000   
4      105      Eva      Mobile  Electronics         3  26000      3000   
5      106    Frank      Tablet  Electronics         2  30000      2500   
6      107    Grace      Laptop  Electronics         1  70000      4000   
7      108   Hannah  Headphones  Accessories         4   2200       400   

        City  
0      Delhi  
1     Mumbai  
2    Chennai  
3    Kolkata  
4      Delhi  
5  Bangalore  
6  Hyderabad  
7     Mumbai

In [140]:
sorted(sales_data)

['Category',
 'City',
 'Customer',
 'Discount',
 'OrderID',
 'Price',
 'Product',
 'Quantity']

In [141]:
sales_data

OrderID Customer     Product     Category  Quantity  Price  Discount  \
0      101    Alice      Laptop  Electronics         1  75000      5000   
1      102      Bob      Mobile  Electronics         2  25000      2000   
2      103  Charlie  Headphones  Accessories         1   2000       200   
3      104    David      Laptop  Electronics         1  80000      8000   
4      105      Eva      Mobile  Electronics         3  26000      3000   
5      106    Frank      Tablet  Electronics         2  30000      2500   
6      107    Grace      Laptop  Electronics         1  70000      4000   
7      108   Hannah  Headphones  Accessories         4   2200       400   

        City  
0      Delhi  
1     Mumbai  
2    Chennai  
3    Kolkata  
4      Delhi  
5  Bangalore  
6  Hyderabad  
7     Mumbai

In [144]:
sales_data['TotalAmount']=sales_data['Quantity']*sales_data['Price']-sales_data['Discount']

In [145]:
sales_data

OrderID Customer     Product     Category  Quantity  Price  Discount  \
0      101    Alice      Laptop  Electronics         1  75000      5000   
1      102      Bob      Mobile  Electronics         2  25000      2000   
2      103  Charlie  Headphones  Accessories         1   2000       200   
3      104    David      Laptop  Electronics         1  80000      8000   
4      105      Eva      Mobile  Electronics         3  26000      3000   
5      106    Frank      Tablet  Electronics         2  30000      2500   
6      107    Grace      Laptop  Electronics         1  70000      4000   
7      108   Hannah  Headphones  Accessories         4   2200       400   

        City  TotalAmount  
0      Delhi        70000  
1     Mumbai        48000  
2    Chennai         1800  
3    Kolkata        72000  
4      Delhi        75000  
5  Bangalore        57500  
6  Hyderabad        66000  
7     Mumbai         8400

In [146]:
sales_data=sales_data.sort_values(by='TotalAmount')

In [147]:
sales_data

OrderID Customer     Product     Category  Quantity  Price  Discount  \
2      103  Charlie  Headphones  Accessories         1   2000       200   
7      108   Hannah  Headphones  Accessories         4   2200       400   
1      102      Bob      Mobile  Electronics         2  25000      2000   
5      106    Frank      Tablet  Electronics         2  30000      2500   
6      107    Grace      Laptop  Electronics         1  70000      4000   
0      101    Alice      Laptop  Electronics         1  75000      5000   
3      104    David      Laptop  Electronics         1  80000      8000   
4      105      Eva      Mobile  Electronics         3  26000      3000   

        City  TotalAmount  
2    Chennai         1800  
7     Mumbai         8400  
1     Mumbai        48000  
5  Bangalore        57500  
6  Hyderabad        66000  
0      Delhi        70000  
3    Kolkata        72000  
4      Delhi        75000

In [148]:
sales_data.tail(3)

OrderID Customer Product     Category  Quantity  Price  Discount     City  \
0      101    Alice  Laptop  Electronics         1  75000      5000    Delhi   
3      104    David  Laptop  Electronics         1  80000      8000  Kolkata   
4      105      Eva  Mobile  Electronics         3  26000      3000    Delhi   

   TotalAmount  
0        70000  
3        72000  
4        75000

In [150]:
sales_data.rename(columns={'TotalAmount':'TotalSales'},inplace=True)

In [151]:
sales_data

OrderID Customer     Product     Category  Quantity  Price  Discount  \
2      103  Charlie  Headphones  Accessories         1   2000       200   
7      108   Hannah  Headphones  Accessories         4   2200       400   
1      102      Bob      Mobile  Electronics         2  25000      2000   
5      106    Frank      Tablet  Electronics         2  30000      2500   
6      107    Grace      Laptop  Electronics         1  70000      4000   
0      101    Alice      Laptop  Electronics         1  75000      5000   
3      104    David      Laptop  Electronics         1  80000      8000   
4      105      Eva      Mobile  Electronics         3  26000      3000   

        City  TotalSales  
2    Chennai        1800  
7     Mumbai        8400  
1     Mumbai       48000  
5  Bangalore       57500  
6  Hyderabad       66000  
0      Delhi       70000  
3    Kolkata       72000  
4      Delhi       75000

In [153]:
Total_Sales=sales_data.groupby('City')['TotalSales'].sum()
Total_Sales

City
Bangalore     57500
Chennai        1800
Delhi        145000
Hyderabad     66000
Kolkata       72000
Mumbai        56400
Name: TotalSales, dtype: int64

In [159]:
Average_price=sales_data.groupby('Product')['TotalSales'].agg(['mean','sum'])
Average_price


mean     sum
Product                         
Headphones   5100.000000   10200
Laptop      69333.333333  208000
Mobile      61500.000000  123000
Tablet      57500.000000   57500

In [163]:
#CorrelationA

correlation=sales_data['Price'].corr(sales_data['Quantity'])
correlation

np.float64(-0.6284250681102551)

In [164]:
correlation=sales_data['Quantity'].corr(sales_data['Discount'])

In [165]:
cols_to_normalize = ["Quantity", "Price"]

# Convert to NumPy array
arr = sales_data[cols_to_normalize].values.astype(float)

# Min-Max normalization
normalized = (arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0)) * 100

# Put back into DataFrame
normalized_df = pd.DataFrame(normalized, columns=["Quantity_norm", "Price_norm"])

# Concatenate with original DataFrame
sales_normalized = pd.concat([sales_data, normalized_df], axis=1)

print(sales_normalized)

   OrderID Customer     Product     Category  Quantity  Price  Discount  \
2      103  Charlie  Headphones  Accessories         1   2000       200   
7      108   Hannah  Headphones  Accessories         4   2200       400   
1      102      Bob      Mobile  Electronics         2  25000      2000   
5      106    Frank      Tablet  Electronics         2  30000      2500   
6      107    Grace      Laptop  Electronics         1  70000      4000   
0      101    Alice      Laptop  Electronics         1  75000      5000   
3      104    David      Laptop  Electronics         1  80000      8000   
4      105      Eva      Mobile  Electronics         3  26000      3000   

        City  TotalSales  Quantity_norm  Price_norm  
2    Chennai        1800      33.333333   29.487179  
7     Mumbai        8400      66.666667   30.769231  
1     Mumbai       48000     100.000000    0.256410  
5  Bangalore       57500       0.000000   93.589744  
6  Hyderabad       66000       0.000000  100.000000  
